export const _PUT_STATUS = '_PUT_STATUS'
export const LIST_ASSETS = 'LIST_ASSETS'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const RESUME_SESSION = 'RESUME_SESSION'